spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/godevtask2?serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      poolName: Hikari
      maximumPoolSize: 20
      minimumIdle: 5
      autoCommit: false
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 2000000